"""add_new_tables_v2

Revision ID: 12841808db97
Revises: b36f224e3448
Create Date: 2026-02-23 15:42:44.401170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12841808db97'
down_revision: Union[str, None] = 'b36f224e3448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('ANTHROPIC', 'OPENAI', name='aiprovider'), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_masked', sa.String(length=20), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('use_platform_key', sa.Boolean(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('risk_thresholds',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('var95_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('var95_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cvar95_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cvar95_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('leverage_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('leverage_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('concentration_warning', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('concentration_danger', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('ai_reports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('RISK_ANALYSIS', 'PERFORMANCE', 'RECOMMENDATIONS', 'CUSTOM', name='reporttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('portfolio_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defi_positions_cache',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.String(length=100), nullable=False),
    sa.Column('protocol_icon', sa.Text(), nullable=True),
    sa.Column('protocol_url', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('LENDING', 'LP', 'STAKING', 'YIELD', 'FARMING', 'BRIDGE', 'OTHER', name='deficategory'), nullable=False),
    sa.Column('position_type', sa.String(length=50), nullable=True),
    sa.Column('asset_symbol', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=True),
    sa.Column('asset_icon', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('chain', sa.String(length=30), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('apy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rewards_pending', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('rewards_pending_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pool_address', sa.String(length=128), nullable=True),
    sa.Column('token0_symbol', sa.String(length=30), nullable=True),
    sa.Column('token0_amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('token1_symbol', sa.String(length=30), nullable=True),
    sa.Column('token1_amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fee_tier', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('in_range', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_balances',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.Enum('SPOT', 'FUTURES', 'MARGIN', 'EARN', 'FUNDING', 'OPTIONS', name='accounttype'), nullable=False),
    sa.Column('free', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('locked', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('total', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('change_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('apy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_earn',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.Enum('FLEXIBLE', 'LOCKED', 'STAKING', 'DUAL_INVESTMENT', 'LAUNCHPOOL', name='earnproducttype'), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('apy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_interest', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('total_interest_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('lock_period_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_redeemable', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_futures',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='futuresside'), nullable=False),
    sa.Column('size', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('margin_type', sa.String(length=20), nullable=True),
    sa.Column('position_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('accumulated_funding', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_subaccounts',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('subaccount_id', sa.String(length=100), nullable=False),
    sa.Column('subaccount_name', sa.String(length=200), nullable=False),
    sa.Column('total_value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('spot_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('futures_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('earn_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_transactions',
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'INTERNAL_TRANSFER', 'TRADE', 'FEE', 'REBATE', 'INTEREST', 'FUNDING_FEE', name='exchangetxtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='exchangetxstatus'), nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('fee', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trade_pair', sa.String(length=30), nullable=True),
    sa.Column('trade_side', sa.String(length=10), nullable=True),
    sa.Column('trade_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('tx_id', sa.String(length=128), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('chain', sa.String(length=30), nullable=True),
    sa.Column('from_address', sa.String(length=128), nullable=True),
    sa.Column('to_address', sa.String(length=128), nullable=True),
    sa.Column('from_account', sa.String(length=50), nullable=True),
    sa.Column('to_account', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_history',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_tokens',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contract_address', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_change_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SEND', 'RECEIVE', 'SWAP', 'APPROVE', 'CONTRACT_CALL', 'STAKE', 'UNSTAKE', 'CLAIM', 'MINT', 'BURN', name='wallettxtype'), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=128), nullable=False),
    sa.Column('to_address', sa.String(length=128), nullable=True),
    sa.Column('token_symbol', sa.String(length=30), nullable=True),
    sa.Column('token_address', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gas_fee', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('gas_fee_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('chain', sa.String(length=30), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('wallet_tokens')
    op.drop_table('notification_history')
    op.drop_table('exchange_transactions')
    op.drop_table('exchange_subaccounts')
    op.drop_table('exchange_futures')
    op.drop_table('exchange_earn')
    op.drop_table('exchange_balances')
    op.drop_table('defi_positions_cache')
    op.drop_table('ai_reports')
    op.drop_table('risk_thresholds')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
